# Generated by Django 5.2.15 on 2026-09-17 09:49

import apps.security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geburtsdatum',
            field=apps.security.fields.EncryptedCharField(blank=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AddField(
            model_name='user',
            name='geburtsort',
            field=apps.security.fields.EncryptedCharField(blank=True, verbose_name='Geburtsort'),
        ),
    ]
