# Generated by Django 6.1.1 on 2026-09-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_geburtsdatum_user_geburtsort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rolle',
            field=models.CharField(choices=[('superadmin', 'Super-Admin'), ('org_admin', 'Org-Admin'), ('trainer', 'Trainer'), ('exam_operator', 'Prüfungsoperator'), ('examiner', 'Pruefer'), ('learner', 'Lernender')], max_length=20),
        ),
    ]
