# Generated by Django 5.2.15 on 2026-09-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_zertifikatdesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='zertifikatdesign',
            name='unterschrift_1',
            field=models.ImageField(blank=True, upload_to='zertifikat_unterschriften/', verbose_name='Unterschrift 1'),
        ),
        migrations.AddField(
            model_name='zertifikatdesign',
            name='unterschrift_2',
            field=models.ImageField(blank=True, upload_to='zertifikat_unterschriften/', verbose_name='Unterschrift 2'),
        ),
    ]
