# Generated by Django 5.2.15 on 2026-09-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_zertifikatdesign_unterschrift_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterneZertifikatsnummer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naechste_nummer', models.PositiveIntegerField(default=5001)),
            ],
        ),
        migrations.AddField(
            model_name='zertifikat',
            name='pdf_datei',
            field=models.FileField(blank=True, upload_to='zertifikate/'),
        ),
        migrations.AddField(
            model_name='zertifikat',
            name='zertifikatsnummer',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True, unique=True),
        ),
    ]
