from django.urls import path

from .views import (
    EinschreibenView,
    KursBewertungCreateView,
    KursDetailView,
    KursKatalogView,
    KursLernenView,
    LernpfadDetailView,
    LernpfadEinschreibenView,
    LernpfadListView,
    TrainerLernpfadCreateView,
    TrainerLernpfadKursCreateView,
    TrainerLernpfadKursDeleteView,
    TrainerLernpfadListView,
    TrainerLernpfadUpdateView,
    LektionAbschliessenView,
    LektionDetailView,
    LektionUebungPruefenView,
    TrainerAbschnittCreateView,
    TrainerKursCreateView,
    TrainerKursListView,
    TrainerKategorieCreateView,
    TrainerKategorieListView,
    TrainerKursUpdateView,
    TrainerUmsatzDashboardView,
    TrainerLektionCreateView,
    TrainerLektionMedienUpdateView,
    TrainerMaterialCreateView,
    TrainerUebungsantwortCreateView,
    TrainerUebungsfrageCreateView,
)


urlpatterns = [
    path("kurse/", KursKatalogView.as_view(), name="course_catalog"),
    path("kurse/<slug:slug>/", KursDetailView.as_view(), name="course_detail"),
    path("kurse/<slug:slug>/einschreiben/", EinschreibenView.as_view(), name="course_enroll"),
    path("kurse/<slug:slug>/bewerten/", KursBewertungCreateView.as_view(), name="course_review"),
    path("kurse/<slug:slug>/lernen/", KursLernenView.as_view(), name="course_learn"),
    path("kurse/<slug:slug>/lernen/<int:lektion_id>/", LektionDetailView.as_view(), name="course_lesson"),
    path(
        "kurse/<slug:slug>/lernen/<int:lektion_id>/abschliessen/",
        LektionAbschliessenView.as_view(),
        name="course_lesson_complete",
    ),
    path(
        "kurse/<slug:slug>/lernen/<int:lektion_id>/uebung/",
        LektionUebungPruefenView.as_view(),
        name="course_lesson_exercise",
    ),
    path("lernpfade/", LernpfadListView.as_view(), name="learning_path_list"),
    path("lernpfade/<slug:slug>/", LernpfadDetailView.as_view(), name="learning_path_detail"),
    path("lernpfade/<slug:slug>/einschreiben/", LernpfadEinschreibenView.as_view(), name="learning_path_enroll"),
    path("trainer/umsatz/", TrainerUmsatzDashboardView.as_view(), name="trainer_revenue_dashboard"),
    path("trainer/kurse/", TrainerKursListView.as_view(), name="trainer_course_list"),
    path("trainer/kurse/neu/", TrainerKursCreateView.as_view(), name="trainer_course_create"),
    path("trainer/kategorien/", TrainerKategorieListView.as_view(), name="trainer_category_list"),
    path("trainer/kategorien/neu/", TrainerKategorieCreateView.as_view(), name="trainer_category_create"),
    path("trainer/kurse/<slug:slug>/", TrainerKursUpdateView.as_view(), name="trainer_course_edit"),
    path("trainer/lernpfade/", TrainerLernpfadListView.as_view(), name="trainer_learning_path_list"),
    path("trainer/lernpfade/neu/", TrainerLernpfadCreateView.as_view(), name="trainer_learning_path_create"),
    path("trainer/lernpfade/<slug:slug>/", TrainerLernpfadUpdateView.as_view(), name="trainer_learning_path_edit"),
    path("trainer/lernpfade/<slug:slug>/kurse/neu/", TrainerLernpfadKursCreateView.as_view(), name="trainer_learning_path_course_create"),
    path("trainer/lernpfade/<slug:slug>/kurse/<int:link_id>/entfernen/", TrainerLernpfadKursDeleteView.as_view(), name="trainer_learning_path_course_delete"),
    path("<slug:org_slug>/trainer/umsatz/", TrainerUmsatzDashboardView.as_view(), name="tenant_trainer_revenue_dashboard"),
    path("<slug:org_slug>/trainer/kurse/", TrainerKursListView.as_view(), name="tenant_trainer_course_list"),
    path("<slug:org_slug>/trainer/lernpfade/", TrainerLernpfadListView.as_view(), name="tenant_trainer_learning_path_list"),
    path(
        "trainer/kurse/<slug:slug>/abschnitte/neu/",
        TrainerAbschnittCreateView.as_view(),
        name="trainer_section_create",
    ),
    path(
        "trainer/kurse/<slug:slug>/abschnitte/<int:abschnitt_id>/lektionen/neu/",
        TrainerLektionCreateView.as_view(),
        name="trainer_lesson_create",
    ),
    path(
        "trainer/kurse/<slug:slug>/lektionen/<int:lektion_id>/medium/",
        TrainerLektionMedienUpdateView.as_view(),
        name="trainer_lesson_media_update",
    ),
    path(
        "trainer/kurse/<slug:slug>/lektionen/<int:lektion_id>/material/neu/",
        TrainerMaterialCreateView.as_view(),
        name="trainer_material_create",
    ),
    path(
        "trainer/kurse/<slug:slug>/lektionen/<int:lektion_id>/uebungsfragen/neu/",
        TrainerUebungsfrageCreateView.as_view(),
        name="trainer_exercise_question_create",
    ),
    path(
        "trainer/kurse/<slug:slug>/uebungsfragen/<int:frage_id>/antworten/neu/",
        TrainerUebungsantwortCreateView.as_view(),
        name="trainer_exercise_answer_create",
    ),
    # Oeffentliche Mandanten-URLs
    path("<slug:org_slug>/kurse/", KursKatalogView.as_view(), name="tenant_course_catalog"),
    path("<slug:org_slug>/kurse/<slug:slug>/", KursDetailView.as_view(), name="tenant_course_detail"),
    path("<slug:org_slug>/kurse/<slug:slug>/einschreiben/", EinschreibenView.as_view(), name="tenant_course_enroll"),
    path("<slug:org_slug>/kurse/<slug:slug>/bewerten/", KursBewertungCreateView.as_view(), name="tenant_course_review"),
    path("<slug:org_slug>/kurse/<slug:slug>/lernen/", KursLernenView.as_view(), name="tenant_course_learn"),
    path("<slug:org_slug>/kurse/<slug:slug>/lernen/<int:lektion_id>/", LektionDetailView.as_view(), name="tenant_course_lesson"),
    path("<slug:org_slug>/kurse/<slug:slug>/lernen/<int:lektion_id>/abschliessen/", LektionAbschliessenView.as_view(), name="tenant_course_lesson_complete"),
    path("<slug:org_slug>/kurse/<slug:slug>/lernen/<int:lektion_id>/uebung/", LektionUebungPruefenView.as_view(), name="tenant_course_lesson_exercise"),
    path("<slug:org_slug>/lernpfade/", LernpfadListView.as_view(), name="tenant_learning_path_list"),
    path("<slug:org_slug>/lernpfade/<slug:slug>/", LernpfadDetailView.as_view(), name="tenant_learning_path_detail"),
    path("<slug:org_slug>/lernpfade/<slug:slug>/einschreiben/", LernpfadEinschreibenView.as_view(), name="tenant_learning_path_enroll"),
]
