# Generated by Django 5.2.15 on 2026-06-25 07:46

import django.db.models.deletion
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('beschreibung', django_quill.fields.QuillField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('sprache', models.CharField(default='de', max_length=10)),
                ('niveau', models.CharField(choices=[('anfaenger', 'Anfaenger'), ('mittel', 'Mittel'), ('fortgeschritten', 'Fortgeschritten')], max_length=20)),
                ('ist_veroeffentlicht', models.BooleanField(default=False)),
                ('ist_kostenlos', models.BooleanField(default=True)),
                ('preis', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurse',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='Einschreibung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eingeschrieben_am', models.DateTimeField(auto_now_add=True)),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True)),
                ('fortschritt_prozent', models.PositiveIntegerField(default=0)),
                ('bezahlt', models.BooleanField(default=True)),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.kurs')),
            ],
            options={
                'verbose_name': 'Einschreibung',
                'verbose_name_plural': 'Einschreibungen',
            },
        ),
        migrations.CreateModel(
            name='Abschnitt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('ist_veroeffentlicht', models.BooleanField(default=True)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abschnitte', to='courses.kurs')),
            ],
            options={
                'verbose_name': 'Abschnitt',
                'verbose_name_plural': 'Abschnitte',
                'ordering': ['reihenfolge'],
            },
        ),
        migrations.CreateModel(
            name='Lektion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('VIDEO', 'Video'), ('DOKUMENT', 'Dokument'), ('TEXT', 'Text/HTML'), ('QUIZ', 'Mini-Quiz')], max_length=20)),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('inhalt', django_quill.fields.QuillField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('datei', models.FileField(blank=True, upload_to='lektionen/')),
                ('dauer_minuten', models.PositiveIntegerField(default=0)),
                ('ist_vorschau', models.BooleanField(default=False)),
                ('abschnitt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lektionen', to='courses.abschnitt')),
            ],
            options={
                'verbose_name': 'Lektion',
                'verbose_name_plural': 'Lektionen',
                'ordering': ['reihenfolge'],
            },
        ),
        migrations.CreateModel(
            name='LektionsFortschritt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abgeschlossen_am', models.DateTimeField(auto_now_add=True)),
                ('einschreibung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.einschreibung')),
                ('lektion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lektion')),
            ],
            options={
                'verbose_name': 'Lektionsfortschritt',
                'verbose_name_plural': 'Lektionsfortschritte',
            },
        ),
        migrations.AddConstraint(
            model_name='einschreibung',
            constraint=models.UniqueConstraint(fields=('nutzer', 'kurs'), name='unique_user_course_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='lektionsfortschritt',
            constraint=models.UniqueConstraint(fields=('einschreibung', 'lektion'), name='unique_lesson_progress'),
        ),
    ]
