# Generated by Django 5.2.15 on 2026-06-26 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_kurs_pruefung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Begleitmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('datei', models.FileField(upload_to='begleitmaterial/')),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('lektion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialien', to='courses.lektion')),
            ],
            options={
                'verbose_name': 'Begleitmaterial',
                'verbose_name_plural': 'Begleitmaterialien',
                'ordering': ['reihenfolge', 'titel'],
            },
        ),
        migrations.CreateModel(
            name='Uebungsfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frage', models.TextField()),
                ('erklaerung', models.TextField(blank=True)),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('aktiv', models.BooleanField(default=True)),
                ('lektion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uebungsfragen', to='courses.lektion')),
            ],
            options={
                'verbose_name': 'Uebungsfrage',
                'verbose_name_plural': 'Uebungsfragen',
                'ordering': ['reihenfolge', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Uebungsantwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwort', models.CharField(max_length=500)),
                ('ist_korrekt', models.BooleanField(default=False)),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antworten', to='courses.uebungsfrage')),
            ],
            options={
                'verbose_name': 'Uebungsantwort',
                'verbose_name_plural': 'Uebungsantworten',
                'ordering': ['reihenfolge', 'id'],
            },
        ),
    ]
