# Generated by Django 5.2.15 on 2026-06-29 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_begleitmaterial_uebungsfrage_uebungsantwort'),
        ('organisations', '0002_organisationdesign_organisationemailkonfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lernpfad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('beschreibung', models.TextField(blank=True)),
                ('ist_veroeffentlicht', models.BooleanField(default=False)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lernpfade', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Lernpfad',
                'verbose_name_plural': 'Lernpfade',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='KursBewertung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sterne', models.PositiveSmallIntegerField(default=5)),
                ('kommentar', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bewertungen', to='courses.kurs')),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kursbewertungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kursbewertung',
                'verbose_name_plural': 'Kursbewertungen',
                'ordering': ['-erstellt_am'],
                'constraints': [models.UniqueConstraint(fields=('kurs', 'nutzer'), name='unique_course_review_user'), models.CheckConstraint(condition=models.Q(('sterne__gte', 1), ('sterne__lte', 5)), name='course_review_stars_1_5')],
            },
        ),
        migrations.CreateModel(
            name='LernpfadEinschreibung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eingeschrieben_am', models.DateTimeField(auto_now_add=True)),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True)),
                ('lernpfad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einschreibungen', to='courses.lernpfad')),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lernpfad_einschreibungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lernpfad-Einschreibung',
                'verbose_name_plural': 'Lernpfad-Einschreibungen',
                'ordering': ['-eingeschrieben_am'],
                'constraints': [models.UniqueConstraint(fields=('nutzer', 'lernpfad'), name='unique_user_learning_path')],
            },
        ),
        migrations.CreateModel(
            name='LernpfadKurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('pflichtkurs', models.BooleanField(default=True)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lernpfad_links', to='courses.kurs')),
                ('lernpfad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pfad_kurse', to='courses.lernpfad')),
            ],
            options={
                'verbose_name': 'Lernpfad-Kurs',
                'verbose_name_plural': 'Lernpfad-Kurse',
                'ordering': ['reihenfolge', 'kurs__titel'],
                'constraints': [models.UniqueConstraint(fields=('lernpfad', 'kurs'), name='unique_learning_path_course')],
            },
        ),
    ]
