# Generated by Django 5.2.15 on 2026-09-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lernpfad_kursbewertung_lernpfadeinschreibung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lektion',
            name='video_thumbnail',
            field=models.ImageField(blank=True, upload_to='lektion-thumbnails/'),
        ),
    ]
