# Generated by Django 5.2.15 on 2026-09-17 12:08

import django.db.models.deletion
from django.db import migrations, models


STANDARD_KATEGORIEN = {
    "IT": ["Softwareentwicklung", "Administration", "Sonstiges"],
    "Wirtschaft": ["Büro und Verwaltung", "Finanzen", "Sonstiges"],
    "Sprachen": ["Deutsch", "Englisch", "Sonstige Sprachen"],
    "Persönliche Entwicklung": ["Kommunikation", "Führung", "Sonstiges"],
    "Gesundheit und Sicherheit": ["Arbeitssicherheit", "Gesundheit", "Sonstiges"],
    "Sonstige": [],
}


def seed_standard_categories(apps, schema_editor):
    Organisation = apps.get_model("organisations", "Organisation")
    Kategorie = apps.get_model("courses", "KursKategorie")
    for organisation in Organisation.objects.all():
        for name, children in STANDARD_KATEGORIEN.items():
            parent, _ = Kategorie.objects.get_or_create(organisation=organisation, parent=None, name=name)
            for child in children:
                Kategorie.objects.get_or_create(organisation=organisation, parent=parent, name=child)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_kurs_angebotstyp'),
        ('organisations', '0008_organisation_demo_inhalte_startbestand'),
    ]

    operations = [
        migrations.CreateModel(
            name='KursKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurskategorien', to='organisations.organisation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unterkategorien', to='courses.kurskategorie')),
            ],
            options={
                'verbose_name': 'Kurskategorie',
                'verbose_name_plural': 'Kurskategorien',
                'ordering': ['parent__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='kurs',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurse', to='courses.kurskategorie'),
        ),
        migrations.AddConstraint(
            model_name='kurskategorie',
            constraint=models.UniqueConstraint(fields=('organisation', 'parent', 'name'), name='unique_course_category_per_org_parent'),
        ),
        migrations.RunPython(seed_standard_categories, migrations.RunPython.noop),
    ]
