from django.urls import path

from .views import (
    ExaminerBewertungView,
    ExaminerQueueView,
    PruefungAblegenView,
    PruefungDetailView,
    PruefungEinschreibenView,
    PruefungErgebnisView,
    PruefungErgebnisListeView,
    PruefungStartView,
    PruefungFortsetzenView,
    PruefungPausierenView,
    PruefungAutosaveView,
    TrainerAntwortCreateView,
    TrainerCSVImportView,
    TrainerFrageCreateView,
    TrainerFragenkatalogCreateView,
    TrainerFragenkatalogDeleteView,
    TrainerFragenkatalogListView,
    TrainerFragenkatalogUpdateView,
    FrageAktivToggleView,
    TrainerKatalogThemenView,
    TrainerPruefungCreateView,
    TrainerPruefungListView,
    TrainerPruefungsFreigabeView,
    TrainerPruefungStatistikView,
    TrainerPruefungErgebnisListeView,
    TrainerPruefungUpdateView,
    TrainerPruefungsbogenPDFView,
    TrainerOfflinePruefungsbogenCreateView,
    TrainerOfflinePruefungsbogenDownloadView,
)


urlpatterns = [
    path("pruefungen/<int:pk>/", PruefungDetailView.as_view(), name="exam_detail"),
    path("pruefungen/<int:pk>/einschreiben/", PruefungEinschreibenView.as_view(), name="exam_enroll"),
    path("pruefungen/<int:pk>/starten/", PruefungStartView.as_view(), name="exam_start"),
    path("pruefungen/<int:pk>/ablegen/<int:versuch_id>/", PruefungAblegenView.as_view(), name="exam_take"),
    path("pruefungen/<int:pk>/ablegen/<int:versuch_id>/fortsetzen/", PruefungFortsetzenView.as_view(), name="exam_resume"),
    path("pruefungen/<int:pk>/ablegen/<int:versuch_id>/pausieren/", PruefungPausierenView.as_view(), name="exam_pause"),
    path("pruefungen/<int:pk>/ablegen/<int:versuch_id>/autosave/", PruefungAutosaveView.as_view(), name="exam_autosave"),
    path("pruefungen/<int:pk>/ergebnis/<int:versuch_id>/", PruefungErgebnisView.as_view(), name="exam_result"),
    path("trainer/fragenkataloge/", TrainerFragenkatalogListView.as_view(), name="trainer_catalog_list"),
    path("trainer/fragenkataloge/neu/", TrainerFragenkatalogCreateView.as_view(), name="trainer_catalog_create"),
    path("trainer/fragenkataloge/<int:pk>/", TrainerFragenkatalogUpdateView.as_view(), name="trainer_catalog_edit"),
    path("trainer/fragenkataloge/<int:pk>/loeschen/", TrainerFragenkatalogDeleteView.as_view(), name="trainer_catalog_delete"),
    path("trainer/fragenkataloge/<int:pk>/themen/", TrainerKatalogThemenView.as_view(), name="trainer_catalog_topics"),
    path("trainer/fragenkataloge/<int:katalog_id>/fragen/neu/", TrainerFrageCreateView.as_view(), name="trainer_question_create"),
    path("trainer/fragenkataloge/<int:katalog_id>/csv/", TrainerCSVImportView.as_view(), name="trainer_catalog_csv"),
    path("trainer/fragen/<int:frage_id>/eintraege/neu/", TrainerAntwortCreateView.as_view(), name="trainer_answer_create"),
    path("trainer/fragen/<int:frage_id>/aktiv-toggle/", FrageAktivToggleView.as_view(), name="trainer_question_toggle_active"),
    path("trainer/pruefungen/", TrainerPruefungListView.as_view(), name="trainer_exam_list"),
    path("trainer/pruefungen/<int:pk>/freigaben/", TrainerPruefungsFreigabeView.as_view(), name="trainer_exam_approvals"),
    path("<slug:org_slug>/trainer/fragenkataloge/", TrainerFragenkatalogListView.as_view(), name="tenant_catalog_list"),
    path("<slug:org_slug>/trainer/pruefungen/", TrainerPruefungListView.as_view(), name="tenant_exam_list"),
    path("trainer/pruefungen/neu/", TrainerPruefungCreateView.as_view(), name="trainer_exam_create"),
    path("trainer/pruefungen/<int:pk>/", TrainerPruefungUpdateView.as_view(), name="trainer_exam_edit"),
    path("trainer/pruefungen/<int:pk>/fragebogen/<str:variante>/pdf/", TrainerPruefungsbogenPDFView.as_view(), name="trainer_exam_paper_pdf"),
    path("trainer/pruefungen/<int:pk>/offline-boegen/erstellen/", TrainerOfflinePruefungsbogenCreateView.as_view(), name="trainer_offline_paper_create"),
    path("trainer/pruefungen/<int:pk>/offline-boegen/<int:archiv_id>/<str:variante>/", TrainerOfflinePruefungsbogenDownloadView.as_view(), name="trainer_offline_paper_download"),
    path("trainer/pruefungen/<int:pk>/statistik/", TrainerPruefungStatistikView.as_view(), name="trainer_exam_stats"),
    path("trainer/pruefungen/<int:pk>/ergebnisse/", TrainerPruefungErgebnisListeView.as_view(), name="trainer_exam_results"),
    path("meine-pruefungsergebnisse/", PruefungErgebnisListeView.as_view(), name="exam_result_list"),
    path("examiner/queue/", ExaminerQueueView.as_view(), name="examiner_queue"),
    path("examiner/queue/<int:pk>/", ExaminerBewertungView.as_view(), name="examiner_review"),
]
