# Generated by Django 5.2.15 on 2026-06-26 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_begleitmaterial_uebungsfrage_uebungsantwort'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zahlung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zahlung_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('zahlungsart', models.CharField(choices=[('stripe', 'Stripe'), ('google_pay', 'Google Pay'), ('bank_transfer', 'Ueberweisung'), ('paypal', 'PayPal')], max_length=30)),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('bezahlt', 'Bezahlt'), ('fehlgeschlagen', 'Fehlgeschlagen'), ('storniert', 'Storniert')], default='offen', max_length=30)),
                ('auszahlungsstatus', models.CharField(choices=[('offen', 'Offen'), ('gemeldet', 'Betreiber informiert'), ('ausgezahlt', 'Ausgezahlt')], default='offen', max_length=30)),
                ('betrag_brutto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plattform_gebuehr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trainer_anteil', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waehrung', models.CharField(default='EUR', max_length=3)),
                ('provider_referenz', models.CharField(blank=True, max_length=255)),
                ('betreiber_notiz', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('bezahlt_am', models.DateTimeField(blank=True, null=True)),
                ('ausgezahlt_am', models.DateTimeField(blank=True, null=True)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zahlungen', to='courses.kurs')),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zahlungen', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_zahlungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
