# Generated by Django 5.2.15 on 2026-06-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zahlungseinstellungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_aktiv', models.BooleanField(default=False)),
                ('stripe_public_key', models.CharField(blank=True, max_length=255)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=255)),
                ('google_pay_aktiv', models.BooleanField(default=False)),
                ('paypal_aktiv', models.BooleanField(default=False)),
                ('paypal_client_id', models.CharField(blank=True, max_length=255)),
                ('paypal_secret', models.CharField(blank=True, max_length=255)),
                ('ueberweisung_aktiv', models.BooleanField(default=True)),
                ('kontoinhaber', models.CharField(blank=True, max_length=200)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('bic', models.CharField(blank=True, max_length=20)),
                ('bankname', models.CharField(blank=True, max_length=200)),
                ('demo_autoconfirm', models.BooleanField(default=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zahlungseinstellungen',
                'verbose_name_plural': 'Zahlungseinstellungen',
            },
        ),
    ]
