# Generated by Django 5.2.15 on 2026-06-29 06:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisationdesign_organisationemailkonfiguration_and_more'),
        ('payments', '0002_zahlungseinstellungen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Audit-Log',
                'verbose_name_plural': 'Audit-Logs',
                'ordering': ['-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechnungsnummer', models.CharField(max_length=40, unique=True)),
                ('rechnungsdatum', models.DateTimeField(auto_now_add=True)),
                ('empfaenger_name', models.CharField(max_length=255)),
                ('empfaenger_email', models.EmailField(max_length=254)),
                ('betrag_netto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('steuerbetrag', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('betrag_brutto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waehrung', models.CharField(default='EUR', max_length=3)),
                ('zahlung', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rechnung', to='payments.zahlung')),
            ],
            options={
                'verbose_name': 'Rechnung/Beleg',
                'verbose_name_plural': 'Rechnungen/Belege',
                'ordering': ['-rechnungsdatum'],
            },
        ),
    ]
