# Generated by Django 5.2.15 on 2026-06-29 10:24

import apps.security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auditlog_rechnung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zahlung',
            name='betreiber_notiz',
            field=apps.security.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='zahlung',
            name='provider_referenz',
            field=apps.security.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='zahlungseinstellungen',
            name='bankname',
            field=apps.security.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='zahlungseinstellungen',
            name='bic',
            field=apps.security.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='zahlungseinstellungen',
            name='iban',
            field=apps.security.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='zahlungseinstellungen',
            name='kontoinhaber',
            field=apps.security.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='zahlungseinstellungen',
            name='paypal_secret',
            field=apps.security.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='zahlungseinstellungen',
            name='stripe_secret_key',
            field=apps.security.fields.EncryptedCharField(blank=True),
        ),
    ]
