# Generated by Django 5.2.15 on 2026-09-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_zahlung_betreiber_notiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zahlungseinstellungen',
            name='payment_aktiv',
            field=models.BooleanField(default=False, verbose_name='Zahlungen aktivieren'),
        ),
        migrations.AlterField(
            model_name='zahlungseinstellungen',
            name='demo_autoconfirm',
            field=models.BooleanField(default=False),
        ),
    ]
