# Generated by Django 5.2.15 on 2026-09-17 08:00

import apps.security.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_organisationemailkonfiguration_einladung_betreff_and_more'),
        ('payments', '0005_zahlungseinstellungen_payment_aktiv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationZahlungseinstellungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_aktiv', models.BooleanField(default=False, verbose_name='Bezahlte Angebote aktivieren')),
                ('stripe_aktiv', models.BooleanField(default=False, verbose_name='Stripe anbieten')),
                ('stripe_public_key', models.CharField(blank=True, max_length=255)),
                ('stripe_secret_key', apps.security.fields.EncryptedCharField(blank=True)),
                ('paypal_aktiv', models.BooleanField(default=False, verbose_name='PayPal anbieten')),
                ('paypal_client_id', models.CharField(blank=True, max_length=255)),
                ('paypal_secret', apps.security.fields.EncryptedCharField(blank=True)),
                ('ueberweisung_aktiv', models.BooleanField(default=False, verbose_name='Bankueberweisung anbieten')),
                ('kontoinhaber', apps.security.fields.EncryptedCharField(blank=True)),
                ('iban', apps.security.fields.EncryptedCharField(blank=True)),
                ('bic', apps.security.fields.EncryptedCharField(blank=True)),
                ('bankname', apps.security.fields.EncryptedCharField(blank=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zahlungseinstellungen', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Organisations-Zahlungseinstellungen',
                'verbose_name_plural': 'Organisations-Zahlungseinstellungen',
            },
        ),
    ]
