# Generated by Django 5.2.15 on 2026-06-25 07:58

import django.db.models.deletion
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('SC', 'Single Choice'), ('MC', 'Multiple Choice'), ('WF', 'Wahr / Falsch'), ('FT', 'Freitext'), ('ZO', 'Zuordnung'), ('SZ', 'Szenario (Case Study)')], max_length=2)),
                ('fragetext', django_quill.fields.QuillField()),
                ('erklaerung', django_quill.fields.QuillField(blank=True)),
                ('schwierigkeit', models.CharField(choices=[('L', 'Leicht'), ('M', 'Mittel'), ('S', 'Schwer')], default='M', max_length=1)),
                ('punkte', models.PositiveIntegerField(default=1)),
                ('eltern_szenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teilfragen', to='exams.frage')),
            ],
            options={
                'verbose_name': 'Frage',
                'verbose_name_plural': 'Fragen',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Antwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antworttext', models.TextField()),
                ('ist_korrekt', models.BooleanField(default=False)),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antworten', to='exams.frage')),
            ],
            options={
                'verbose_name': 'Antwort',
                'verbose_name_plural': 'Antworten',
                'ordering': ['reihenfolge'],
            },
        ),
        migrations.CreateModel(
            name='Fragenkatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=300)),
                ('beschreibung', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Fragenkatalog',
                'verbose_name_plural': 'Fragenkataloge',
                'ordering': ['titel'],
            },
        ),
        migrations.AddField(
            model_name='frage',
            name='fragenkatalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragen', to='exams.fragenkatalog'),
        ),
        migrations.CreateModel(
            name='FragenTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Fragen-Tag',
                'verbose_name_plural': 'Fragen-Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='frage',
            name='tags',
            field=models.ManyToManyField(blank=True, to='exams.fragentag'),
        ),
        migrations.CreateModel(
            name='Pruefung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=300)),
                ('beschreibung', models.TextField(blank=True)),
                ('anzahl_fragen', models.PositiveIntegerField()),
                ('zeitlimit_minuten', models.PositiveIntegerField(blank=True, null=True)),
                ('bestehensgrenze_prozent', models.PositiveIntegerField(default=70)),
                ('max_versuche', models.PositiveIntegerField(blank=True, null=True)),
                ('zufaellige_fragenreihenfolge', models.BooleanField(default=True)),
                ('zufaellige_antwortfolge', models.BooleanField(default=True)),
                ('kein_zurueck', models.BooleanField(default=False)),
                ('ist_aktiv', models.BooleanField(default=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('fragenkatalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.fragenkatalog')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Pruefung',
                'verbose_name_plural': 'Pruefungen',
                'ordering': ['titel'],
            },
        ),
        migrations.CreateModel(
            name='PruefungsVersuch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versuch_nummer', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('LAUFEND', 'Laufend'), ('AUSSTEHEND', 'Freitext-Bewertung ausstehend'), ('ABGESCHLOSSEN', 'Abgeschlossen'), ('ABGELAUFEN', 'Zeitlimit ueberschritten'), ('ABGEBROCHEN', 'Abgebrochen')], default='LAUFEND', max_length=20)),
                ('gestartet_am', models.DateTimeField(auto_now_add=True)),
                ('abgeschlossen_am', models.DateTimeField(blank=True, null=True)),
                ('punkte_erreicht', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('punkte_gesamt', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('prozent_erreicht', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bestanden', models.BooleanField(default=False)),
                ('fragen_reihenfolge', models.JSONField(default=list)),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pruefung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.pruefung')),
            ],
            options={
                'verbose_name': 'Pruefungsversuch',
                'verbose_name_plural': 'Pruefungsversuche',
                'ordering': ['-gestartet_am'],
            },
        ),
        migrations.CreateModel(
            name='TeilnehmerAntwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freitext_antwort', models.TextField(blank=True)),
                ('freitext_punkte', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('freitext_kommentar', models.TextField(blank=True)),
                ('freitext_bewertet_am', models.DateTimeField(blank=True, null=True)),
                ('zuordnung_json', models.JSONField(blank=True, null=True)),
                ('ist_korrekt', models.BooleanField(null=True)),
                ('punkte_vergeben', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ausgewaehlte_antworten', models.ManyToManyField(blank=True, to='exams.antwort')),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.frage')),
                ('freitext_bewertet_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bewertungen', to=settings.AUTH_USER_MODEL)),
                ('versuch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antworten', to='exams.pruefungsversuch')),
            ],
            options={
                'verbose_name': 'Teilnehmerantwort',
                'verbose_name_plural': 'Teilnehmerantworten',
            },
        ),
        migrations.CreateModel(
            name='ZuordnungsPaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkes_element', models.CharField(max_length=500)),
                ('rechtes_element', models.CharField(max_length=500)),
                ('reihenfolge', models.PositiveIntegerField(default=0)),
                ('frage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zuordnungen', to='exams.frage')),
            ],
            options={
                'verbose_name': 'Zuordnungspaar',
                'verbose_name_plural': 'Zuordnungspaare',
                'ordering': ['reihenfolge'],
            },
        ),
        migrations.AddConstraint(
            model_name='fragentag',
            constraint=models.UniqueConstraint(fields=('name', 'organisation'), name='unique_question_tag_org'),
        ),
        migrations.AddConstraint(
            model_name='pruefungsversuch',
            constraint=models.UniqueConstraint(fields=('nutzer', 'pruefung', 'versuch_nummer'), name='unique_user_exam_attempt'),
        ),
        migrations.AddConstraint(
            model_name='teilnehmerantwort',
            constraint=models.UniqueConstraint(fields=('versuch', 'frage'), name='unique_attempt_question_answer'),
        ),
    ]
