# Generated by Django 5.2.15 on 2026-09-16 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PruefungsThemenquote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl_fragen', models.PositiveIntegerField(verbose_name='Anzahl Fragen')),
                ('pruefung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themenquoten', to='exams.pruefung')),
                ('thema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruefungsquoten', to='exams.fragentag')),
            ],
            options={
                'verbose_name': 'Themenquote',
                'verbose_name_plural': 'Themenquoten',
                'ordering': ['thema__name'],
                'constraints': [models.UniqueConstraint(fields=('pruefung', 'thema'), name='unique_exam_topic_quota')],
            },
        ),
    ]
