# Generated by Django 5.2.15 on 2026-09-16 08:40

import apps.security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_pruefungsthemenquote'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruefungsversuch',
            name='einsehbar_bis',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pruefungsversuch',
            name='ergebnis_verschluesselt',
            field=apps.security.fields.EncryptedTextField(blank=True),
        ),
    ]
