# Generated by Django 5.2.15 on 2026-09-17 07:40

import django.db.models.deletion
import django_quill.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_pruefungsanmeldung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='frage',
            name='bewertungshinweis',
            field=django_quill.fields.QuillField(blank=True, verbose_name='Bewertungsschema'),
        ),
        migrations.CreateModel(
            name='PruefungsbogenArchiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('fragen_reihenfolge', models.JSONField(default=list)),
                ('teilnehmer_pdf', models.FileField(upload_to='pruefungsboegen/teilnehmer/')),
                ('loesung_pdf', models.FileField(upload_to='pruefungsboegen/loesungen/')),
                ('erstellt_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pruefung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_boegen', to='exams.pruefung')),
            ],
            options={
                'verbose_name': 'Offline-Pruefungsbogen',
                'verbose_name_plural': 'Offline-Pruefungsboegen',
                'ordering': ['-erstellt_am'],
            },
        ),
    ]
