# Generated by Django 5.2.15 on 2026-09-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_frage_bewertungshinweis_pruefungsbogenarchiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruefung',
            name='externe_nummern_ende',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pruefung',
            name='externe_nummern_naechste',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pruefung',
            name='externe_nummern_prefix',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='pruefung',
            name='zertifikatsnummernart',
            field=models.CharField(choices=[('INTERN', 'Interne fortlaufende Nummer'), ('EXTERN', 'Externer Nummernbereich')], default='INTERN', max_length=10),
        ),
    ]
