# Generated by Django 6.1.1 on 2026-09-21 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_pruefung_externe_nummern_ende_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='frage',
            name='aktiv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pruefung',
            name='pdf_antwortzeilen',
            field=models.PositiveIntegerField(default=6, verbose_name='Antwortzeilen im PDF'),
        ),
        migrations.AddField(
            model_name='pruefung',
            name='pdf_fusszeile',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='PDF-Fusszeile'),
        ),
        migrations.AddField(
            model_name='pruefungsversuch',
            name='aktive_phase_begonnen_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pruefungsversuch',
            name='aktive_sekunden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pruefungsversuch',
            name='letzte_aktivitaet_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pruefungsversuch',
            name='pausiert_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Pruefungsversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versionsnummer', models.PositiveIntegerField()),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pruefung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versionen', to='exams.pruefung')),
            ],
            options={
                'verbose_name': 'Pruefungsversion',
                'verbose_name_plural': 'Pruefungsversionen',
                'ordering': ['-versionsnummer'],
            },
        ),
        migrations.AddField(
            model_name='pruefungsversuch',
            name='pruefungsversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versuche', to='exams.pruefungsversion'),
        ),
        migrations.CreateModel(
            name='PruefungsFreigabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freigegeben_am', models.DateTimeField(auto_now_add=True)),
                ('widerrufen_am', models.DateTimeField(blank=True, null=True)),
                ('freigegeben_von', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erteilte_pruefungsfreigaben', to=settings.AUTH_USER_MODEL)),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruefungsfreigaben', to=settings.AUTH_USER_MODEL)),
                ('pruefung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freigaben', to='exams.pruefung')),
            ],
            options={
                'verbose_name': 'Pruefungsfreigabe',
                'verbose_name_plural': 'Pruefungsfreigaben',
                'ordering': ['nutzer__last_name', 'nutzer__first_name', 'nutzer__username'],
                'constraints': [models.UniqueConstraint(fields=('pruefung', 'nutzer'), name='unique_exam_release_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='pruefungsversion',
            constraint=models.UniqueConstraint(fields=('pruefung', 'versionsnummer'), name='unique_exam_version_number'),
        ),
    ]
