# Generated by Django 6.0.6 on 2026-06-28 08:47

import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#12315f', help_text='Navigationselemente, Überschriften, Rahmen', max_length=20, verbose_name='Primärfarbe')),
                ('secondary_color', models.CharField(default='#f28c28', help_text='Buttons, Highlights, Fortschrittsbalken', max_length=20, verbose_name='Akzentfarbe')),
                ('navbar_farbe', models.CharField(default='#0c2448', max_length=20, verbose_name='Navigationsleisten-Farbe')),
                ('hintergrund_farbe', models.CharField(default='#f6f8fb', max_length=20, verbose_name='Seiten-Hintergrundfarbe')),
                ('logo', models.ImageField(blank=True, help_text='Wird in Navbar und Kurskatalog angezeigt (PNG/SVG empfohlen)', upload_to='org_design/logos/', verbose_name='Organisations-Logo')),
                ('favicon', models.ImageField(blank=True, upload_to='org_design/favicons/', verbose_name='Favicon (16×16 oder 32×32 px)')),
                ('custom_css', models.TextField(blank=True, help_text='Erweiterte Anpassungen – nur für erfahrene Nutzer', verbose_name='Eigenes CSS')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Organisations-Design',
                'verbose_name_plural': 'Organisations-Designs',
            },
        ),
        migrations.CreateModel(
            name='OrganisationEmailKonfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktiv', models.BooleanField(default=False, help_text='Wenn deaktiviert, wird der Plattform-Standard-SMTP genutzt.', verbose_name='Eigenen E-Mail-Server verwenden')),
                ('absender_name', models.CharField(blank=True, max_length=200, verbose_name='Absendername')),
                ('absender_email', models.EmailField(blank=True, max_length=254, verbose_name='Absender-E-Mail')),
                ('antwort_email', models.EmailField(blank=True, help_text='Zweite Adresse – z.B. support@meinefirma.de', max_length=254, verbose_name='Antwort-E-Mail (Reply-To)')),
                ('smtp_host', models.CharField(blank=True, max_length=200, verbose_name='SMTP-Host')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP-Port')),
                ('smtp_user', models.CharField(blank=True, max_length=200, verbose_name='SMTP-Benutzername')),
                ('smtp_password', models.CharField(blank=True, max_length=500, verbose_name='SMTP-Passwort')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='STARTTLS verwenden (Port 587)')),
                ('smtp_use_ssl', models.BooleanField(default=False, verbose_name='SSL verwenden (Port 465)')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_konfiguration', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'E-Mail-Konfiguration',
                'verbose_name_plural': 'E-Mail-Konfigurationen',
            },
        ),
        migrations.CreateModel(
            name='OrganisationStartseite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktiv', models.BooleanField(default=False, help_text='Wenn deaktiviert, wird die Plattform-Standardseite angezeigt.', verbose_name='Eigene Startseite aktivieren')),
                ('hero_titel', models.CharField(blank=True, max_length=200, verbose_name='Haupt-Überschrift')),
                ('hero_untertitel', models.CharField(blank=True, max_length=500, verbose_name='Unter-Überschrift')),
                ('hero_bild', models.ImageField(blank=True, upload_to='org_design/hero/', verbose_name='Hero-Hintergrundbild')),
                ('hero_button_text', models.CharField(blank=True, default='Kurse entdecken', max_length=100, verbose_name='Schaltflächen-Text')),
                ('inhalt', django_quill.fields.QuillField(blank=True, verbose_name='Seiteninhalt (WYSIWYG)')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startseite', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Organisations-Startseite',
                'verbose_name_plural': 'Organisations-Startseiten',
            },
        ),
    ]
