# Generated by Django 5.2.15 on 2026-06-29 10:24

import apps.security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisationdesign_organisationemailkonfiguration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationemailkonfiguration',
            name='smtp_password',
            field=apps.security.fields.EncryptedCharField(blank=True, verbose_name='SMTP-Passwort'),
        ),
    ]
