# Generated by Django 5.2.15 on 2026-09-17 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_frage_bewertungshinweis_pruefungsbogenarchiv'),
        ('organisations', '0004_organisation_weiterleitungs_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='einladung',
            name='pruefung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='einladungen', to='exams.pruefung', verbose_name='Zertifikatspruefung'),
        ),
    ]
