# Generated by Django 5.2.15 on 2026-09-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_einladung_pruefung'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationemailkonfiguration',
            name='einladung_betreff',
            field=models.CharField(default='Einladung zu {{ organisation }}', max_length=200),
        ),
        migrations.AddField(
            model_name='organisationemailkonfiguration',
            name='einladung_text',
            field=models.TextField(default='Hallo,\n\nSie wurden zu {{ organisation }} eingeladen. Bitte nehmen Sie die Einladung innerhalb von 7 Tagen an:\n{{ einladungslink }}\n\nFreundliche Gruesse\n{{ organisation }}'),
        ),
        migrations.AddField(
            model_name='organisationemailkonfiguration',
            name='passwort_reset_betreff',
            field=models.CharField(default='Passwort zuruecksetzen bei {{ organisation }}', max_length=200),
        ),
        migrations.AddField(
            model_name='organisationemailkonfiguration',
            name='passwort_reset_text',
            field=models.TextField(default='Hallo,\n\nSie haben angefordert, Ihr Passwort fuer {{ organisation }} zurueckzusetzen. Nutzen Sie dazu diesen Link:\n{{ passwort_reset_link }}\n\nWenn Sie dies nicht angefordert haben, koennen Sie diese E-Mail ignorieren.'),
        ),
    ]
