# Generated by Django 5.2.15 on 2026-09-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_organisationemailkonfiguration_einladung_betreff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='ist_demo_organisation',
            field=models.BooleanField(default=False, verbose_name='Demo-Organisation'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model("organisations", "Organisation").objects.filter(
                slug__in=["demo-org", "demo-organisation"]
            ).update(ist_demo_organisation=True),
            migrations.RunPython.noop,
        ),
    ]
