# Generated by Django 5.2.15 on 2026-09-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0007_organisation_ist_demo_organisation'),
        ('courses', '0007_kurs_angebotstyp'),
        ('exams', '0006_frage_bewertungshinweis_pruefungsbogenarchiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='demo_inhalte_startbestand',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: [
                apps.get_model("organisations", "Organisation").objects.filter(pk=org.pk).update(
                    demo_inhalte_startbestand=(
                        apps.get_model("courses", "Kurs").objects.filter(organisation_id=org.pk).count()
                        + apps.get_model("exams", "Pruefung").objects.filter(organisation_id=org.pk).count()
                    )
                )
                for org in apps.get_model("organisations", "Organisation").objects.filter(ist_demo_organisation=True)
            ],
            migrations.RunPython.noop,
        ),
    ]
